# Data Analytics Project: `"Sales Data Analysis using NumPy"`

## Project Description:

You are given sales data for a store over 50 days.

Each sale has:

* The day spanning for ten weeks (1 to 50)

* With sales made five days a week, as a result of the store opening from Mondays from Fridays

* The amount of sale in dollars

## You must use NumPy to:

* Analyze total, average sales

* Find best-selling day

* Find days with sales above average

* Group sales by weeks

# Step 1: Import Libraries

In [133]:
# import libraries
import numpy as np

# Step 2: Create Synthetic Sales Data

In [134]:
# create a synthetic sales data

# set random seed for repeatability
np.random.seed(42)

# generate random sales amounts $100 and $1000
sales = np.random.randint(100, 1000, size=50)

# print sales data
print("Sales Data for 50 Days:")
print(sales) 


Sales Data for 50 Days:
[202 535 960 370 206 171 800 120 714 221 566 314 430 558 187 472 199 971
 763 230 761 408 869 443 591 513 905 485 291 376 260 559 413 121 352 847
 956 660 574 158 610 781 575 799 882 289 786 662 975 666]


# Step 3: Basic Sales Analysis

### Total Sales

In [135]:
# Total sales
total_sales = np.sum(sales)
print(f"Total Sales in 50 Days: ${total_sales}")

Total Sales in 50 Days: $26556


### Average Daily Sales

In [136]:
# Average Daily Sales
average_sales = np.mean(sales)
print(f"Average Sales in 50 Days: ${average_sales:.2f}")

Average Sales in 50 Days: $531.12


### Maximum Sales (Best-selling day)

In [137]:
# Maximum Sales (Best-selling days)
max_sales = np.max(sales)
best_selling_day = np.argmax(sales) + 1

print(f"Best-Selling Day: Day {best_selling_day} with sales of ${max_sales}")

Best-Selling Day: Day 49 with sales of $975


### Minimum Sales (Worst-selling day)

In [138]:
# Minimum Sales (Worst-selling day)
min_sales = np.min(sales)
worst_selling_day = np.argmin(sales) + 1

print(f"Worst-Selling Day: Day {worst_selling_day} with sales of ${min_sales}")

Worst-Selling Day: Day 8 with sales of $120


# Step 4: Find Days with Above Average Sales

In [139]:
above_average_days = np.where(sales > average_sales)
print(f"Days with Above Average Sales: {above_average_days[0] + 1}")

Days with Above Average Sales: [ 2  3  7  9 11 14 18 19 21 23 25 27 32 36 37 38 39 41 42 43 44 45 47 48
 49 50]


### Sales on those days:

In [140]:
# Getting the sales on those days
print("Sales on Above Average Days:")
print(sales[above_average_days])

Sales on Above Average Days:
[535 960 800 714 566 558 971 763 761 869 591 905 559 847 956 660 574 610
 781 575 799 882 786 662 975 666]


# Step 5: Group Sales into Weeks

* Reshape the 50 days into 10 weeks:

In [141]:
# Grouping days into weeks

# Reshape the 50 days into 10 weeks
weekly_sales = sales.reshape(10, 5)   # 10 weeks, 5 days per week
print("Weekly Sales Data:")
print(weekly_sales)

Weekly Sales Data:
[[202 535 960 370 206]
 [171 800 120 714 221]
 [566 314 430 558 187]
 [472 199 971 763 230]
 [761 408 869 443 591]
 [513 905 485 291 376]
 [260 559 413 121 352]
 [847 956 660 574 158]
 [610 781 575 799 882]
 [289 786 662 975 666]]


### Weekly totals:

In [142]:
# Weekly totals
weekly_totals = np.sum(weekly_sales, axis=1)
print("Total Sales per week:")
print(weekly_totals)

Total Sales per week:
[2273 2026 2055 2635 3072 2570 1705 3195 3647 3378]


### Best week:

In [143]:
# Best performing week
best_week = np.argmax(weekly_totals) + 1
print(f"Best Week: Week {best_week} with total sales of ${weekly_totals[best_week-1]}")

Best Week: Week 9 with total sales of $3647
